name: Validate API Version

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # necesario para comparar con la rama anterior

      - name: Get current API version
        id: current
        run: |
          VERSION=$(grep -Eo 'version\\s*=\\s*["v0-9.]+' src/main/java/**/OpenApiConfig.java || true)
          if [ -z "$VERSION" ]; then
            VERSION=$(grep -E '^springdoc.info.version=' src/main/resources/application.properties | cut -d'=' -f2)
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get previous API version (from main)
        id: previous
        run: |
          git fetch origin main
          PREV_VERSION=$(git show origin/main:src/main/java/**/OpenApiConfig.java | grep -Eo 'version\\s*=\\s*["v0-9.]+' || true)
          if [ -z "$PREV_VERSION" ]; then
            PREV_VERSION=$(git show origin/main:src/main/resources/application.properties | grep -E '^springdoc.info.version=' | cut -d'=' -f2)
          fi
          echo "version=$PREV_VERSION" >> $GITHUB_OUTPUT

      - name: Compare API versions
        run: |
          echo "Current:  ${{ steps.current.outputs.version }}"
          echo "Previous: ${{ steps.previous.outputs.version }}"

          if [ "${{ steps.current.outputs.version }}" == "${{ steps.previous.outputs.version }}" ]; then
            echo "❌ API version must be incremented before pushing changes."
            exit 1
          else
            echo "✅ API version changed — OK to merge."
          fi

